[package]
name = "e7030e-embedded-system-design"
version = "0.1.0"
authors = ["Viktor From <viktor.from91@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
